version: "3"
services:
  sqlboiler-playground-db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sekret
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: sqlboiler
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 55432:5432
